name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: yarn

      - name: build and run tests
        run: |
          yarn e2e
          yarn e2e:report
